DROP TABLE IF EXISTS simulations CASCADE;
DROP TABLE IF EXISTS demandes CASCADE;
DROP TABLE IF EXISTS profils CASCADE;
DROP TABLE IF EXISTS produits CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP SEQUENCE IF EXISTS demandes_reference_seq;
DROP FUNCTION IF EXISTS generate_reference();

CREATE TABLE categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), slug TEXT UNIQUE NOT NULL, nom TEXT NOT NULL, nom_pt TEXT, description TEXT, icone TEXT, image_url TEXT, commission_min DECIMAL(4,2) DEFAULT 5.0, commission_max DECIMAL(4,2) DEFAULT 8.0, ordre INTEGER DEFAULT 0, actif BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now());

INSERT INTO categories (slug, nom, nom_pt, description, icone, commission_min, commission_max, ordre) VALUES ('vehicules', 'Veículos', 'Veículos', 'Carros de empresa, pick-ups, minibus, utilitários', 'car', 5.0, 6.0, 1), ('informatique', 'Informática', 'Informática', 'PC, servidores, NAS, switches, Wi-Fi', 'laptop', 6.0, 7.0, 2), ('telephonie', 'Telefonia', 'Telefonia', 'Smartphones, IPBX, tablets, terminais de pagamento', 'phone', 6.0, 8.0, 3), ('mobilier', 'Mobiliário', 'Mobiliário', 'Mobiliário de escritório, hoteleiro, restaurante, open-space', 'armchair', 5.0, 7.0, 4), ('chr', 'Equipamento CHR', 'Equipamento CHR', 'Fornos profissionais, refrigeração, máquinas de café', 'utensils', 6.0, 8.0, 5);

CREATE TABLE produits (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), categorie_id UUID REFERENCES categories(id) ON DELETE CASCADE, slug TEXT UNIQUE NOT NULL, nom TEXT NOT NULL, marque TEXT, modele TEXT, description TEXT, description_courte TEXT, prix_achat DECIMAL(12,2) NOT NULL, valeur_residuelle_pct DECIMAL(4,2) DEFAULT 5.0, durees_disponibles INTEGER[] DEFAULT '{24,36,48,60}', images TEXT[], specifications JSONB, tags TEXT[], en_vedette BOOLEAN DEFAULT false, actif BOOLEAN DEFAULT true, stock_disponible BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

CREATE TABLE profils (id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, prenom TEXT, nom TEXT, telephone TEXT, type_client TEXT CHECK (type_client IN ('entreprise','profession_liberale','administration','particulier_pro')), nom_entreprise TEXT, siret TEXT, secteur TEXT, role TEXT DEFAULT 'client' CHECK (role IN ('client','admin','banque')), created_at TIMESTAMPTZ DEFAULT now());

CREATE TABLE demandes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), reference TEXT UNIQUE NOT NULL, utilisateur_id UUID REFERENCES profils(id), produit_id UUID REFERENCES produits(id), prix_bien DECIMAL(12,2) NOT NULL, duree_mois INTEGER NOT NULL CHECK (duree_mois IN (24,36,48,60)), loyer_mensuel_estime DECIMAL(10,2) NOT NULL, valeur_residuelle DECIMAL(10,2), taux_commission DECIMAL(4,2), client_prenom TEXT, client_nom TEXT, client_email TEXT NOT NULL, client_telephone TEXT, client_type TEXT, client_nom_entreprise TEXT, client_siret TEXT, client_secteur TEXT, client_ile TEXT, fournisseur_souhaite TEXT, statut TEXT DEFAULT 'nouvelle' CHECK (statut IN ('nouvelle','en_etude','approuvee','refusee','en_cours','terminee','annulee')), documents_urls TEXT[], notes_admin TEXT, banque_partenaire TEXT, created_at TIMESTAMPTZ DEFAULT now(), updated_at TIMESTAMPTZ DEFAULT now());

CREATE SEQUENCE demandes_reference_seq START 1;

CREATE OR REPLACE FUNCTION generate_reference() RETURNS TRIGGER AS $$ BEGIN NEW.reference := 'CVL-' || EXTRACT(YEAR FROM now()) || '-' || LPAD(nextval('demandes_reference_seq')::TEXT, 4, '0'); RETURN NEW; END; $$ LANGUAGE plpgsql;

CREATE TRIGGER set_reference BEFORE INSERT ON demandes FOR EACH ROW EXECUTE FUNCTION generate_reference();

CREATE TABLE simulations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), utilisateur_id UUID REFERENCES profils(id), produit_id UUID REFERENCES produits(id), prix_bien DECIMAL(12,2), duree_mois INTEGER, loyer_mensuel DECIMAL(10,2), session_id TEXT, created_at TIMESTAMPTZ DEFAULT now());

ALTER TABLE profils ENABLE ROW LEVEL SECURITY;
ALTER TABLE demandes ENABLE ROW LEVEL SECURITY;
ALTER TABLE simulations ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE produits ENABLE ROW LEVEL SECURITY;

CREATE POLICY "profil_self" ON profils FOR ALL USING (auth.uid() = id);
CREATE POLICY "demandes_owner" ON demandes FOR SELECT USING (auth.uid() = utilisateur_id OR EXISTS (SELECT 1 FROM profils WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "demandes_insert" ON demandes FOR INSERT WITH CHECK (true);
CREATE POLICY "demandes_update_admin" ON demandes FOR UPDATE USING (EXISTS (SELECT 1 FROM profils WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "categories_public_read" ON categories FOR SELECT USING (actif = true);
CREATE POLICY "produits_public_read" ON produits FOR SELECT USING (actif = true);

-- Veículos
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, specifications) VALUES ((SELECT id FROM categories WHERE slug='vehicules'), 'toyota-hilux-4x4', 'Toyota Hilux 4x4 Cabine Dupla', 'Toyota', 'Hilux', 'Pick-up robusto ideal para construção civil e ilhas remotas', 42000, '{24,36,48,60}', true, '{"motor":"2.8L Diesel","potencia":"204 cv","transmissao":"4WD","lugares":5,"carga_util":"1000 kg"}');
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, specifications) VALUES ((SELECT id FROM categories WHERE slug='vehicules'), 'mitsubishi-l200', 'Mitsubishi L200 Utilitário', 'Mitsubishi', 'L200', 'Utilitário polivalente para empresas de serviços', 35000, '{24,36,48,60}', false, '{"motor":"2.4L Diesel","potencia":"154 cv","transmissao":"4WD","lugares":5}');
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, specifications) VALUES ((SELECT id FROM categories WHERE slug='vehicules'), 'minibus-toyota-hiace', 'Toyota HiAce Minibus 15 lugares', 'Toyota', 'HiAce', 'Transporte de pessoal e shuttles hoteleiros', 55000, '{36,48,60}', true, '{"lugares":15,"motor":"2.8L Diesel","ar_condicionado":true,"uso":"Transporte coletivo"}');
-- Informática
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, specifications) VALUES ((SELECT id FROM categories WHERE slug='informatique'), 'dell-latitude-14-pro', 'Dell Latitude 14 Pro (lote 10)', 'Dell', 'Latitude 14', 'Pack 10 portáteis profissionais para equipa comercial', 12000, '{24,36,48}', true, '{"quantidade":10,"processador":"Intel Core i5","ram":"16 GB","armazenamento":"512 GB SSD","ecra":"14 polegadas"}');
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, specifications) VALUES ((SELECT id FROM categories WHERE slug='informatique'), 'serveur-hp-proliant', 'HP ProLiant DL380 Servidor', 'HP', 'ProLiant DL380', 'Servidor rack de alto desempenho para PME', 18000, '{36,48,60}', false, '{"processador":"2x Intel Xeon","ram":"64 GB","armazenamento":"4x 2TB HDD","rack":"2U"}');
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, specifications) VALUES ((SELECT id FROM categories WHERE slug='informatique'), 'switch-cisco-24ports', 'Cisco Catalyst Switch 24 portas', 'Cisco', 'Catalyst 2960', 'Infraestrutura de rede para escritório ou hotel', 8500, '{24,36,48}', false, '{"portas":24,"poe":true,"velocidade":"1 Gbps","gerenciavel":true}');
-- Telefonia
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, specifications) VALUES ((SELECT id FROM categories WHERE slug='telephonie'), 'iphone-15-pro-lot', 'iPhone 15 Pro (lote 20)', 'Apple', 'iPhone 15 Pro', 'Frota móvel para equipa comercial ou hoteleira', 28000, '{24,36}', true, '{"quantidade":20,"armazenamento":"256 GB","cor":"Titânio natural","garantia":"24 meses"}');
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, specifications) VALUES ((SELECT id FROM categories WHERE slug='telephonie'), 'ipbx-grandstream', 'Central IPBX Grandstream UCM6302', 'Grandstream', 'UCM6302', 'Central telefónica IP para PME até 100 extensões', 4500, '{24,36,48}', false, '{"extensoes_max":100,"extensoes_sip":true,"ivr":true,"gravacao":true}');
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, specifications) VALUES ((SELECT id FROM categories WHERE slug='telephonie'), 'tablettes-samsung-lot', 'Samsung Galaxy Tab A9 (lote 15)', 'Samsung', 'Galaxy Tab A9', 'Tablets para receção hoteleira ou ponto de venda', 9000, '{24,36}', false, '{"quantidade":15,"ecra":"10.5 polegadas","armazenamento":"128 GB","wifi":true}');
-- Mobiliário
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, specifications) VALUES ((SELECT id FROM categories WHERE slug='mobilier'), 'agencement-bureau-openspace', 'Open-Space 20 postos de trabalho', 'Kinnarps', 'Suite Pro', 'Mobiliário completo para open-space profissional', 22000, '{36,48,60}', true, '{"postos":20,"estilo":"Contemporâneo"}');
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, specifications) VALUES ((SELECT id FROM categories WHERE slug='mobilier'), 'mobilier-chambre-hotel', 'Kit Quarto de Hotel Standard (10 quartos)', 'Custom', 'Hotel Line', 'Mobiliário completo para 10 quartos de hotel 3 estrelas', 35000, '{36,48,60}', true, '{"quartos":10,"norma":"Hotelaria 3 estrelas"}');
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, specifications) VALUES ((SELECT id FROM categories WHERE slug='mobilier'), 'salle-conference', 'Sala de Conferências 20 pessoas', 'Steelcase', 'Meeting Pro', 'Mesa oval + cadeirões + ecrã interativo 75 polegadas', 18000, '{36,48}', false, '{"capacidade":20,"ecra":"75 polegadas 4K","videoconferencia":true}');
-- Equipamento CHR
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, images, specifications) VALUES ((SELECT id FROM categories WHERE slug='chr'), 'four-convection-vapeur', 'Forno de Convecção/Vapor 4 tabuleiros', 'Leasymat', 'CV-4GN', 'Forno profissional convecção/vapor para restaurante', 684, '{24,36,48}', true, ARRAY['https://leasymat.com/wp-content/uploads/2025/04/sp-005-61656e68b2750.jpg'], '{"tabuleiros":4,"formato":"60x40 cm","alimentacao":"400V","certificacao":"CE"}');
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, images, specifications) VALUES ((SELECT id FROM categories WHERE slug='chr'), 'vitrine-refrigeree-morris', 'Vitrina Refrigerada Morris 2.0', 'Leasymat', 'Morris 2.0', 'Vitrina refrigerada profissional para pastelaria', 2338, '{24,36,48}', false, ARRAY['https://leasymat.com/wp-content/uploads/2025/04/7486.0075-9556-scaled.jpg'], '{"comprimento":"2 metros","iluminacao":"LED","niveis":3}');
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, images, specifications) VALUES ((SELECT id FROM categories WHERE slug='chr'), 'machine-expresso-3-pistons', 'Máquina de Expresso 3 pistões – 540 chávenas/h', 'Leasymat', 'EX-3P', 'Máquina de expresso profissional de alto volume', 2069, '{24,36,48}', true, ARRAY['https://leasymat.com/wp-content/uploads/2025/04/sp-1005-09100003.jpg'], '{"capacidade":"540 chávenas/hora","pistoes":3}');
INSERT INTO produits (categorie_id, slug, nom, marque, modele, description_courte, prix_achat, durees_disponibles, en_vedette, images, specifications) VALUES ((SELECT id FROM categories WHERE slug='chr'), 'cuisiniere-5-bruleurs', 'Fogão Profissional 5 queimadores a gás', 'Leasymat', 'CUI-5BR', 'Fogão a gás 5 queimadores com forno para cozinha profissional', 3575, '{24,36,48}', true, ARRAY['https://leasymat.com/wp-content/uploads/2025/04/7003.0920-9888.jpg'], '{"queimadores":5,"tipo":"Gás","forno":"Integrado"}');
